name: CI/CD Lacrei Saúde (Dinâmico)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/lacrei-app:latest
            ${{ secrets.DOCKER_USERNAME }}/lacrei-app:${{ github.sha }}

  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Descobrir IP de Staging
        id: get_ip
        run: |
          # Busca o IP Publico da instancia que tem a Tag Name = lacrei-devops-staging e está rodando
          IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=lacrei-devops-staging" "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --output text)
          
          echo "IP Encontrado: $IP"
          echo "STAGING_IP=$IP" >> $GITHUB_ENV

      - name: Deploy em Staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.STAGING_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker stop lacrei-app || true
            sudo docker rm lacrei-app || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/lacrei-app:latest
            sudo docker run -d --name lacrei-app --restart always -p 3000:3000 -e NODE_ENV=staging ${{ secrets.DOCKER_USERNAME }}/lacrei-app:latest

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Descobrir IP de Produção
        id: get_ip
        run: |
          IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=lacrei-devops-production" "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --output text)
          
          echo "IP Encontrado: $IP"
          echo "PROD_IP=$IP" >> $GITHUB_ENV

      - name: Deploy em Produção
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.PROD_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker stop lacrei-app || true
            sudo docker rm lacrei-app || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/lacrei-app:latest
            sudo docker run -d --name lacrei-app --restart always -p 3000:3000 -e NODE_ENV=production ${{ secrets.DOCKER_USERNAME }}/lacrei-app:latest